import ContentLoader, { Rect } from "react-content-loader/native";
import { PLACEHOLDER, GRAY_DARK } from "_styles/colors";
import { scaleSize } from "_styles/mixins";

const HomeLoader = (props) => (
  <ContentLoader
    speed={2}
    width="100%"
    height="100%"
    backgroundColor={PLACEHOLDER}
    foregroundColor={GRAY_DARK}
  >
    <Rect
      x={scaleSize(10)}
      y={scaleSize(20)}
      rx={scaleSize(22)}
      ry={scaleSize(22)}
      width={scaleSize(92)}
      height={scaleSize(35)}
    />
    <Rect
      x={scaleSize(110)}
      y={scaleSize(20)}
      rx={scaleSize(22)}
      ry={scaleSize(22)}
      width={scaleSize(92)}
      height={scaleSize(35)}
    />
    <Rect
      x={scaleSize(210)}
      y={scaleSize(20)}
      rx={scaleSize(22)}
      ry={scaleSize(22)}
      width={scaleSize(92)}
      height={scaleSize(35)}
    />
    <Rect
      x={scaleSize(310)}
      y={scaleSize(20)}
      rx={scaleSize(22)}
      ry={scaleSize(22)}
      width={scaleSize(120)}
      height={scaleSize(35)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(75)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(200)}
      height={scaleSize(28)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(125)}
      rx={scaleSize(7)}
      ry={scaleSize(7)}
      width={scaleSize(250)}
      height={scaleSize(250)}
    />
    <Rect
      x={scaleSize(270)}
      y={scaleSize(125)}
      rx={scaleSize(7)}
      ry={scaleSize(7)}
      width={scaleSize(250)}
      height={scaleSize(250)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(400)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(170)}
      height={scaleSize(22)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(440)}
      rx={scaleSize(7)}
      ry={scaleSize(7)}
      width={scaleSize(170)}
      height={scaleSize(170)}
    />
    <Rect
      x={scaleSize(190)}
      y={scaleSize(440)}
      rx={scaleSize(7)}
      ry={scaleSize(7)}
      width={scaleSize(170)}
      height={scaleSize(170)}
    />
    <Rect
      x={scaleSize(370)}
      y={scaleSize(440)}
      rx={scaleSize(7)}
      ry={scaleSize(7)}
      width={scaleSize(170)}
      height={scaleSize(170)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(620)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(170)}
      height={scaleSize(10)}
    />
    <Rect
      x={scaleSize(190)}
      y={scaleSize(620)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(170)}
      height={scaleSize(10)}
    />

    <Rect
      x={scaleSize(370)}
      y={scaleSize(620)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(170)}
      height={scaleSize(10)}
    />
    <Rect
      x={scaleSize(10)}
      y={scaleSize(635)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(130)}
      height={scaleSize(10)}
    />
    <Rect
      x={scaleSize(190)}
      y={scaleSize(635)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(130)}
      height={scaleSize(10)}
    />

    <Rect
      x={scaleSize(370)}
      y={scaleSize(635)}
      rx={scaleSize(3)}
      ry={scaleSize(3)}
      width={scaleSize(130)}
      height={scaleSize(10)}
    />
  </ContentLoader>
);

export default HomeLoader;
